language: scala
scala:
  - 2.10.6
jdk:
  - openjdk7

install:
  - git clone https://github.com/bdzimmer/util-scala ../util-scala
  - git clone https://github.com/bdzimmer/pixel-editor ../pixel-editor
  - git clone https://github.com/bdzimmer/orbits ../orbits
script: sbt ++$TRAVIS_SCALA_VERSION test it:test